 # 🐼 Pandas — Table of Contents

```text
                         ┌─────────────────────┐
                         │       PANDAS        │
                         │  Data Analysis Tool │
                         └──────────┬──────────┘
                                    │
        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌───────────────┐           ┌────────────────┐          ┌─────────────────┐
│ 1. Introduction│           │ 2. Data        │          │ 3. Reading &    │
│    to Pandas   │           │    Structures  │          │    Writing Data │
└───────┬────────┘           └───────┬────────┘          └────────┬────────┘
        │                            │                            │
        ▼                            ▼                            ▼
  • What is Pandas            • Series (1D)                • CSV
  • Why Pandas?               • DataFrame (2D)              • Excel
  • Installation              • Creating DataFrame           • JSON
  • import pandas as pd       • Creating Series              • Text files


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 4. Exploring    │        │ 5. Selecting    │         │ 6. Filtering    │
│    Data         │        │    Data         │         │    Data         │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • head()                   • Select columns            •Single Conditions
   • tail()                   • Select rows               • Boolean indexing
   • shape                    • loc[]                     • Multiple conditions
   • info()                   • iloc[]                    • isin()
   • describe()               • at / iat                  • Text filtering


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 7. Missing Data │        │ 8. Data         │         │ 9. Grouping &   │
│                 │        │    Manipulation │         │    Aggregation  │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • isnull()                 • Add columns              • groupby()
   • notnull()                • Rename columns            • sum()
   • dropna()                 • Drop columns              • mean()
   • fillna()                 • Apply functions            • count()
   • replace()                • Sorting                    • Multiple aggregations


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 10. Merging &   │        │ 11. Time Series │         │ 12. Real-World  │
│     Joining     │        │     Data        │         │     Projects    │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • merge()                  • Datetime                  • Data Cleaning
   • join()                   • to_datetime()             • EDA
   • concat()                 • Date operations            • Data Analysis
   • Join types               • Resampling                • Data Visualization
                              • Time-based filtering       • Real-world datasets


                         ┌─────────────────────┐
                         │   PANDA'S GOAL      │
                         │                     │
                         │ Data → Clean →      │
                         │ Analyze → Insights  │
                         └─────────────────────┘
```

# <h1 style="color:pink">***Chapter-01:Introduction to pandas***</h1>

## 1) what is pandas

## 2)why pandas

## 3) installation of pandas

# <h1 style=color:pink>***Chapter-02 : Data structure in pandas***</h1>

## <h1 style=color:yellow>***1) pandas series:***</h1>A Pandas Series is a one-dimensional, labeled array capable of holding any data type 


```
0    2
1    3
2    4
3    5
4    6

It looks like  single column in an Excel spreadsheet or a database table.

By default, Pandas creates a numeric index starting from 0.

if we want diffrent index instead of numeric then we can give extra parameter index while creating a series 


```

In [2]:
# creating a panads series using list 
import pandas as pd 
ser=pd.Series([2,3,4,5,6])
print(ser)

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [9]:
# using array
import pandas as pd 
import array 
my_arr=array.array("i",[2,3,4,5,6])
print(pd.Series(my_arr))

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [6]:
# using numpy array
import numpy as np 
import pandas as pd 

my_arr=np.array([2,3,1,8])
print(pd.Series(my_arr))

0    2
1    3
2    1
3    8
dtype: int64

In [13]:
# using dictinary 
import pandas as pd 

pd.Series({
      "name":"shahid",
      "age":24,
      "college":"IIT"
})

name       shahid
age            24
college       IIT
dtype: object

## Question practice

In [17]:
# ques1: cretae a series with custom name instead of numeric index index 

import numpy as np 
import pandas as pd 
my_arr=np.array([2,3,1,8])
print(pd.Series(my_arr,index=["a","b","c","d"]))

a    2
b    3
c    1
d    8
dtype: int64

In [ ]:
## ques: can we create series using multidimentinal list or array
ans:no bcz seris is a one dimentinal array so while creating it we must pass a one dimentinal list,array

## 2) Data frame in pandas 

## Pandas DataFrame is a two-dimensional, tabular data structure
## Think of it exactly like a spreadheet / Excel sheet or a SQL database table


## default index(label) of row is numeric starting with 0

In [10]:
# creating dataframes using dict 

import pandas as pd

my_dic = { "name": ["shahid","raj","rakesh"], "age": [24,30,35], "sallary": [40000,30000,45000] }
df = pd.DataFrame(my_dic)
print(df)

     name  age  sallary
0  shahid   24    40000
1     raj   30    30000
2  rakesh   35    45000

In [3]:
# creating data frames using list 
import pandas as pd
my_list=[["shahid",24,"Delhi university"],["fahad",26,"iit"],["sanajy",18,"Delhi university"]]
pd.DataFrame(my_list)

        0   1                 2
0  shahid  24  Delhi university
1   fahad  26               iit
2  sanajy  18  Delhi university

In [5]:
# now we can give the custom labels to rows and columns 

pd.DataFrame(my_list,columns=["name","age","College"])
pd.DataFrame(my_list,columns=["name","age","sallery"],index=["a","b","c"])

     name  age           sallery
a  shahid   24  Delhi university
b   fahad   26               iit
c  sanajy   18  Delhi university

In [2]:
# creating a data frames by reading a csv file 
import pandas as pd 

df=pd.read_csv("train.csv")
print(df)

     PassengerId  Survived  Pclass                                               Name     Sex  ...  Parch            Ticket     Fare Cabin  Embarked
0              1         0       3                            Braund, Mr. Owen Harris    male  ...      0         A/5 21171   7.2500   NaN         S
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  ...      0          PC 17599  71.2833   C85         C
2              3         1       3                             Heikkinen, Miss. Laina  female  ...      0  STON/O2. 3101282   7.9250   NaN         S
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  ...      0            113803  53.1000  C123         S
4              5         0       3                           Allen, Mr. William Henry    male  ...      0            373450   8.0500   NaN         S
..           ...       ...     ...                                                ...     ...  ...    ...               ...      ...   ...       ...
886          887         0       2                              Montvila, Rev. Juozas    male  ...      0            211536  13.0000   NaN         S
887          888         1       1                       Graham, Miss. Margaret Edith  female  ...      0            112053  30.0000   B42         S
888          889         0       3           Johnston, Miss. Catherine Helen "Carrie"  female  ...      2        W./C. 6607  23.4500   NaN         S
889          890         1       1                              Behr, Mr. Karl Howell    male  ...      0            111369  30.0000  C148         C
890          891         0       3                                Dooley, Mr. Patrick    male  ...      0            370376   7.7500   NaN         Q

[891 rows x 12 columns]

#  <h1 style="color:pink">Chatpter -04 Exploring the data in data frames</h1>

a)Head()

b)Tail()

In [ ]:
c)Sample()

e)info()

f)shape()

g)describe()

# <h1 style=color:pink>***Chapter-05 Selecting the data***</h1>

## a) selecting whole data fram

In [3]:
import pandas as pd 
df=pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## b)Selecting Columns

```
df[["column_name"]]        # Single column (as Series)
df[["col1", "col2"]]     # Multiple columns (as DataFrame)

In [4]:
import pandas as pd 

df=pd.read_csv("train.csv")


# slect the single col 

# df[["Pclass"]]

# multiple col 

df[["Pclass","Survived","Name"]]

     Pclass  Survived                                               Name
0         3         0                            Braund, Mr. Owen Harris
1         1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         3         1                             Heikkinen, Miss. Laina
3         1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         3         0                           Allen, Mr. William Henry
..      ...       ...                                                ...
886       2         0                              Montvila, Rev. Juozas
887       1         1                       Graham, Miss. Margaret Edith
888       3         0           Johnston, Miss. Catherine Helen "Carrie"
889       1         1                              Behr, Mr. Karl Howell
890       3         0                                Dooley, Mr. Patrick

[891 rows x 3 columns]

## b)Selecting Rows

```
Use .loc[] (label-based) and .iloc[] (position-based):

df.loc[0]                # selecting a rows whose name or lable is 0
df.iloc[0]               # selecting first rows by postion  (by default postion is start from 0)


note:balel is name used to identity the row and column and it can be numeric or string 

but postion is always numeric and start with 0 irrespective of whatevr the label is 

```

In [5]:
# selecting a rows  using loc (label-based)
#syntax:df.loc[list]

# select onw rows
df.loc[[0]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [6]:
# selcting a mutiple rows 
df.loc[[1,3,4]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
# selecting a rows using iloc (postion-based)

df.iloc[[1]] # second rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [8]:
# selecting a multiple rows 
df.iloc[[1,3,5]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

# <h1 style="color:green">***question : print the data frame and see the rows label ,is it numeric ? if yes then***</h1>
### 1)give custom label 
### 1) select the rows using loc 
### 3) select the rows using iloc
### 4) select a particular cell using loc and iloc

In [15]:
# creating a data frame with custom lebel
import pandas as pd

my_dic = { "name": ["shahid","raj","rakesh"], "age": [24,30,35], "sallary": [40000,30000,45000] }
df = pd.DataFrame(my_dic,index=["a","b","c"])
df

     name  age  sallary
a  shahid   24    40000
b     raj   30    30000
c  rakesh   35    45000

In [18]:
df.loc[["b"]]

  name  age  sallary
b  raj   30    30000

In [16]:

df.loc[["a"]]

     name  age  sallary
a  shahid   24    40000

In [19]:
# selecting a row using iloc 
df.iloc[[0]]

     name  age  sallary
a  shahid   24    40000

In [20]:
# selecting a row using iloc 
df.iloc[[1]]

  name  age  sallary
b  raj   30    30000

## c)select a cell (selecting a particula element of box in a data frame)

In [25]:
df.loc["b","name"]

'raj'

In [24]:
df.loc["a","sallary"]

np.int64(40000)

In [28]:
df.iloc[0,0]

'shahid'

## d)slicing

In [29]:
df.loc["a":"b","name":"age"] # in case of loc last index will be included

     name  age
a  shahid   24
b     raj   30

In [30]:
df.iloc[0:1,0:1] # in case of iloc last index will be excluded

     name
a  shahid

## e)Fast Access: .at and .iat
## These are optimized for single element or cell  access:

```
df.at[0, "Name"]       # Fast label-based access
df.iat[0, 1]           # Fast position-based access

In [31]:
df.at["a","name"]

'shahid'

# Practice

## what is diffrence b/w loc and iloc

In [54]:
# loc and iloc both are used to access the row from the given data frame 
# but loc is label based and iloc is postion based 

import pandas as pd 
df=pd.read_csv("train.csv")
df.head()
df.loc[[0,2,4]] #eccess on the basis of label
df.iloc[0:3,0:3]  # access on the basis of postion

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3

## ques:what is the diffrence b/w at and iat

### at and iat both are used to access cell from the given data frame 
###  but at is label based and iat is postion based  

### it is more optimesd and fast access comapre to loc and iloc

# <h1 style=color:pink>***Chapter-06 Filtering the data  Based on condition***</h1>


### Data filtering ka matlab hai: DataFrame mein se sirf woh rows select karna jo hamari condition satisfy karti hain.

###  For example, agar 5 students ka data hai aur humein sirf un students ko dekhna hai jinke marks 70 se zyada hain, toh hum filtering use karenge.

## 1. Single Conditions
## Comparison operators: >, <,<=,>=, ==, !=

## ques: Hum ek students DataFrame banate hain. Isi data ko use karke saare filtering concepts seekhenge.

In [32]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Sara", "Rahul", "Neha", "Imran"],
    "Age": [20, 22, 19, 24, 21],
    "Marks": [65, 85, 45, 92, 75],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
})

df

    Name  Age  Marks    City
0   Aman   20     65   Delhi
1   Sara   22     85  Mumbai
2  Rahul   19     45   Delhi
3   Neha   24     92    Pune
4  Imran   21     75  Mumbai

## Suppose humein check karna hai ki kaunse students ke marks 70 se zyada hain.

In [35]:
df["Marks"]>70

0    False
1     True
2    False
3     True
4     True
Name: Marks, dtype: bool

In [4]:
df

    Name  Age  Marks    City
1   Sara   22     85  Mumbai
3   Neha   24     92    Pune
4  Imran   21     75  Mumbai

In [8]:
df[df["Marks"] > 70]

    Name  Age  Marks    City
1   Sara   22     85  Mumbai
3   Neha   24     92    Pune
4  Imran   21     75  Mumbai

## Suppose humein 70 se zyada marks wale students ke sirf names aur marks chahiye.

In [49]:
df[df["Marks"]>70][["Name","Marks"]]

    Name  Marks
1   Sara     85
3   Neha     92
4  Imran     75

## Question: Humein sirf un students ka data chahiye jinki age 21 se kam hai. Kaunsi Pandas expression sahi hai?

### df[df["Age"] < 21]


#### df["Age" < 21]


#### df[df["Age"] > 21]


#### df["Age"] = 21

# 2) Multiple Conditions in Pandas

#### &( boollean and operator) :  Dono conditions True honi chahiye 
#### |( boolean or operator ) :  Koi ek condition True honi chahiye 
#### ~ |(boolean not operator) :  Condition ka result reverse karta hai

## a). AND (&) — Dono conditions true honi chahiye
#### Example: students jinke marks 70 se zyada hain aur city Mumbai hai.

In [11]:
df[(df["Marks"] > 70) & (df["City"] == "Mumbai")]

    Name  Age  Marks    City
1   Sara   22     85  Mumbai
4  Imran   21     75  Mumbai

## b). OR (|) — Koi ek condition true honi chahiye
## Example: un students ko find karo jo Delhi mein rehte hain ya jinke marks 80 se zyada hain.

In [12]:
df[(df["City"] == "Delhi") | (df["Marks"] > 80)]

    Name  Age  Marks    City
0   Aman   20     65   Delhi
1   Sara   22     85  Mumbai
2  Rahul   19     45   Delhi
3   Neha   24     92    Pune

## c). NOT (~) — Condition ko reverse karna
## Example: un students ko find karo jo Delhi mein nahi rehte.

In [52]:
df["City"]==

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2172210885.py, line 1)

# 5. Practice exercise


```
question1
Un students ka data filter karne ke liye correct code select karo jinke marks 60 se zyada hain aur age 21 se kam hai.

df[(df["Marks"] > 60) & (df["Age"] < 21)]


df[(df["Marks"] > 60) | (df["Age"] < 21)]


df[df["Marks"] > 60 and df["Age"] < 21]

``` 
Question 2 
Un students ko select karo jo Pune mein rehte hain ya jinke marks 70 se zyada hain.

df[(df["City"] == "Pune") & (df["Marks"] > 70)]


df[(df["City"] == "Pune") | (df["Marks"] > 70)]


df[(df["City"] == "Pune") and (df["Marks"] > 70)]

```
question 3
un students ko select karna hai:
- Jinki age 20 ya usse zyada hai.
- Jinke marks 70 ya usse zyada hain.
- Jo Mumbai mein rehte hain.

# 3) isin() 
## ek column mein multiple values ko ek saath filter  karte hain

In [ ]:
# syntax: 
df[df["column"].isin([value1, value2, value3])]

In [ ]:
df[df["City"].isin(["Delhi", "Pune"])]

In [ ]:
df[~df["City"].isin(["Delhi", "Pune"])]

```
4. Practice question
Question: Humein un students ka data chahiye jo Delhi ya Pune mein rehte hain. Kaunsa code correct hai?

df[df["City"].isin(["Delhi", "Pune"])]


df[df["City"] == ["Delhi", "Pune"]]


df[df["City"].isin("Delhi", "Pune")]

## 4)Text Filtering in Pandas

```
strings ya text ke basis par rows filter karenge. Jaise names mein koi word search karna, kisi prefix se start hone wale names find karna, ya kisi particular ending wale names select karna.

In [ ]:
df[df["Name"].str.contains("a", case=False)]

In [ ]:
df[df["Name"].str.contains("an", case=False)]

In [16]:
df[df["Name"].str.startswith("a", na=False, case=False)]

TypeError: StringMethods.startswith() got an unexpected keyword argument 'case'

In [17]:
df[df["Name"].str.lower().str.startswith("a", na=False)]

   Name  Age  Marks   City
0  Aman   20     65  Delhi

In [18]:
df[df["Name"].str.endswith("a", na=False)]

   Name  Age  Marks    City
1  Sara   22     85  Mumbai
3  Neha   24     92    Pune

In [19]:
df[df["Name"].str.lower().str.endswith("a", na=False)]

   Name  Age  Marks    City
1  Sara   22     85  Mumbai
3  Neha   24     92    Pune